### ISSUE TITLE
Daikon Compilation Error 

### ISSUE THREAD

**Issue by nitinkp470** [codespecs/daikon#205]
After cloning the github repo
make compile
Error exists both in ubuntu 16 and 18.

`cd daikon/chicory && java -ea -cp /home/ubu16/hls/daikon/java/lib/*:/home/ubu16/hls/daikon/java daikon.Chicory --verbose --debug daikon.chicory.Test > Test.log
Exception in thread "main" java.lang.ClassFormatError: Multiple RuntimeVisibleAnnotations attributes for method in class file org/plumelib/reflection/Signatures
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at daikon.chicory.DaikonWriter.methodName(DaikonWriter.java:176)
	at daikon.chicory.DaikonWriter.methodEntryName(DaikonWriter.java:46)
	at daikon.chicory.DeclWriter.print_decl_class(DeclWriter.java:275)
	at daikon.chicory.DeclWriter.printDeclClass(DeclWriter.java:120)
	at daikon.chicory.Runtime.process_new_classes(Runtime.java:468)
	at daikon.chicory.Runtime.enter(Runtime.java:240)
	at daikon.chicory.Test.main(Test.java:16)
Makefile:448: recipe for target 'daikon/chicory/inv_out.diff' failed
make[4]: *** [daikon/chicory/inv_out.diff] Error 1
make[4]: Leaving directory '/home/ubu16/hls/daikon/java'
Makefile:440: recipe for target 'ChicoryPremain.jar' failed
make[3]: *** [ChicoryPremain.jar] Error 2
make[3]: *** Deleting file 'ChicoryPremain.jar'
make[3]: Leaving directory '/home/ubu16/hls/daikon/java'
Makefile:405: recipe for target 'all_directly' failed
make[2]: *** [all_directly] Error 2
make[2]: Leaving directory '/home/ubu16/hls/daikon/java'
Makefile:388: recipe for target 'all_stop_on_error' failed
make[1]: *** [all_stop_on_error] Error 2
make[1]: Leaving directory '/home/ubu16/hls/daikon/java'
Makefile:157: recipe for target 'compile-java' failed
make: *** [compile-java] Error 2`

**Comment by markro49** [comment]
I have checked that as of the c18e0668938b7786ebac0304cc451a75299a54ec commit chicory builds and chicory-test runs correctly on Java 11 on Ubuntu 18.04.   Please note that while Chicory works on Java 11, DynComp does not.  The work to support DynComp on Java 11 is in progress.
