### ISSUE TITLE
@CallerSensitive annotation expected

### ISSUE THREAD

**Issue by comentator** [codespecs/daikon#268]
I have a problem with Daikon, where it tells me that it expects a @CallerSensitive annotation.
I have one case where i try to Instrument Junit Tests using **org.junit.runner.JUnitCore** so i cannot add the missing Annotation.
Is there a way to circumvent this?

### Setup
uname -a
```
Linux *********** 5.4.44-1-MANJARO #1 SMP PREEMPT Wed Jun 3 14:48:07 UTC 2020 x86_64 GNU/Linux
```
java -version
```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```
Daikon: 5.8.2 (downloaded from the website).

mvn -version
```
Apache Maven 3.6.3 (NON-CANONICAL_2019-11-27T20:26:29Z_root)
Maven home: /opt/maven
Java version: 1.8.0_252, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-openjdk/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.44-1-manjaro", arch: "amd64", family: "unix"
```

### Steps to reproduce
For this i just chose a random Junit project from Github
```shell
rm -rf example
mkdir example
cd example

git clone git@github.com:ThomasJaspers/java-junit-sample.git
cd java-junit-sample
mvn install


java -cp ./target/junitsample-0.0.1-SNAPSHOT.jar:$DAIKONDIR/daikon.jar daikon.DynComp org.junit.runner.JUnitCore com.codecentric.sample.store.service.CustomerService
```

### My Output
```java
JUnit version 4.13
Exception in thread "main" java.lang.InternalError: CallerSensitive annotation expected at frame 1
	at sun.reflect.Reflection.getCallerClass(Native Method)
	at sun.reflect.Reflection.getCallerClass(Reflection.java)
	at java.lang.Class.forName(Class.java:263)
	at com.sun.proxy.$Proxy3.<clinit>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:739)
	at sun.reflect.annotation.AnnotationParser$1.run(AnnotationParser.java:305)
	at sun.reflect.annotation.AnnotationParser$1.run(AnnotationParser.java:303)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(AccessController.java)
	at sun.reflect.annotation.AnnotationParser.annotationForMap(AnnotationParser.java:303)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:293)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258)
	at java.lang.Class.isAnnotationPresent(Class.java:3425)
	at org.junit.runner.notification.RunNotifier.wrapIfNotThreadSafe(RunNotifier.java:50)
	at org.junit.runner.notification.RunNotifier.addFirstListener(RunNotifier.java:247)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:134)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:77)
	at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
```

**Comment by markro49** [comment]
You had a small typo in your instructions (choJUintCore instead of JUnitCore) but I was able to reproduce the problem.  No diagnosis as yet.

**Comment by markro49** [comment]
I tried running the test case with an uninstrumented version of the Java runtime (--rt-file=none) - that failed with a ClassNotFoundException.  Changing CustomerServiceTest to CustomerService seems to be the answer.  After correcting that, the test still failed exactly as described in https://github.com/codespecs/daikon/issues/200.  I think I will investigate this issue first.

**Comment by comentator** [comment]
Sorry i need to update my Instructions again.
CustomerService is not a test class and CustomerServiceTest can't be found because maven doesn't include test classes by default, i will create another Repository and give new instructions. 
Sorry for the inconveniences

**Comment by markro49** [comment]
Actually, I think I have figured all that out.  You also needed to add mockito to class path.

**Comment by comentator** [comment]
New Instructions,
but probably Obsolete as it produces exactly the same output as in #200 and Considering your message you have it probably all figuered out already.
```shell 
rm -rf example
mkdir example
cd example

git clone git@github.com:comentator/exampleTestJar.git
cd exampleTestJar
mvn install

wget https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
wget https://repo1.maven.org/maven2/junit/junit/4.13/junit-4.13.jar

java -cp junit-4.13.jar:hamcrest-core-1.3.jar:target/my-app-1-tests.jar:$DAIKONDIR/daikon.jar daikon.DynComp org.junit.runner.JUnitCore ExampleTest
```

**Comment by markro49** [comment]
Want to try your new test case but it looks like comentator/exampleTestJar is not public.

**Comment by comentator** [comment]
Oh yeah sorry,
i just changed it to public

**Comment by comentator** [comment]
With my example it works fine. 
So i think the issue can be closed now, thanks for your work.

**Comment by markro49** [comment]
I also verified that exampleTestJar works correctly with latest DynComp.  The first example,  CustomerServiceTest, still fails due to competing byte code instrumentation tools, but we now output a warning to that effect.
