### ISSUE TITLE
assert running kvasir-tests/DisambigTest with -ea

### ISSUE THREAD

**Issue by markro49** [codespecs/daikon#68]
We currently do not run with -ea on the daikon portion of a kvasir regression test.  When I tried, they all ran ok except for DisambigTest.

java -ea -Xmx2500M -XX:MaxPermSize=960M -cp /homes/gws/markro/invariants/daikon7/daikon.jar daikon.Daikon --no_text_output --no_show_progress --config_option daikon.derive.Derivation.disable_derived_variables=true --config ../config.txt --config_option daikon.DynamicConstants.OneOf_only=true  daikon-output/DisambigTest.dyncomp.decls daikon-output/DisambigTest.dtrace.orig -o daikon-output/DisambigTest.inv.gz
Daikon version 5.3.9, released August 1, 2016; http://plse.cs.washington.edu/daikon.
(read 1 decls file)                                                            .
Processing trace data; reading 1 dtrace file:
[12:18:26 PM]: Finished reading daikon-output/DisambigTest.dtrace.orig
Exception in thread "main" java.lang.AssertionError: ProglangType (var ::globalTB.string_A type int[]) must be pseudo-array for OneOfSequence
        at daikon.inv.unary.sequence.OneOfSequence.<init>(OneOfSequence.java:107)
        at daikon.inv.unary.sequence.OneOfSequence.instantiate_dyn(OneOfSequence.java:126)
        at daikon.inv.unary.sequence.OneOfSequence.instantiate_dyn(OneOfSequence.java:38)
        at daikon.inv.Invariant.instantiate(Invariant.java:1859)
        at daikon.DynamicConstants.instantiate_oneof(DynamicConstants.java:1129)
        at daikon.DynamicConstants.post_process(DynamicConstants.java:944)
        at daikon.Daikon.process_data(Daikon.java:2147)
        at daikon.Daikon.mainHelper(Daikon.java:614)
        at daikon.Daikon.main(Daikon.java:492)
../Makefile.common:110: recipe for target 'daikon-output/DisambigTest.inv.gz' failed
make: *** [daikon-output/DisambigTest.inv.gz] Error 1

 I'm sorry, but I couldn't make much progress on this one.  And it's entirely possible that the problem is in the decl/dtrace files kvasir produces.

**Comment by mernst** [comment]
Strictly speaking, this is a Kvasir bug.
[Section A.3.3](https://plse.cs.washington.edu/daikon/download/doc/developer.html#Variable-declarations) of the developer manual says:

>  `array <dim>`
>     The number of array dimensions inherited or declared by this variable. The valid values are 0 or 1. This should be specified for any variable that has multiple values. 

but the generated .decls file contains:

```
  variable ::globalTB.string_A
    var-kind field string_A
    enclosing-var ::globalTB
    rep-type int[]
    dec-type int[]
```

We could fix the problem by having Daikon automatically set the number of array dimentions to 1 when the rep-type is an array, or by having Kvasir output the `array <dim>` declaration as required in the manual.

**Comment by markro49** [comment]
I will look at the Kvasir side.  Thanks for the analysis.

**Comment by mernst** [comment]
OK.  I'm curious why this is only showing up in one test case.

**Comment by markro49** [comment]
https://github.com/codespecs/daikon/commit/2c40c15f83100ee84897fdafd0ec00a431c704a2
https://github.com/codespecs/fjalar/commit/e854c8df210873959e0180a88c08729de8e74bbb
These commits resolve this issue.
